#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_EXPORTER_USER WITH PASSWORD '$POSTGRES_EXPORTER_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_EXPORTER_USER;
    GRANT pg_monitor TO $POSTGRES_EXPORTER_USER;
EOSQL